In [1]:
import numpy

import cicada.arithmetic
import cicada.encoding

In [2]:
encoding = cicada.encoding.FixedPoint()
encoding

cicada.encoding.fixedpoint.FixedPoint(precision=16)

In [3]:
field = cicada.arithmetic.Field()
field

cicada.arithmetic.Field(order=18446744073709551557)

In [4]:
encoding.encode(1, field)

array(65536, dtype=object)

In [5]:
encoding.encode([1, 2], field)

array([65536, 131072], dtype=object)

In [6]:
encoding.encode([[1, 2], [3, 4]], field)

array([[65536, 131072],
       [196608, 262144]], dtype=object)

In [7]:
encoding.encode(0.5, field)

array(32768, dtype=object)

In [8]:
encoding.encode(-1, field)

array(18446744073709486021, dtype=object)

In [9]:
try:
    encoding.encode(2**63, field)
except Exception as e:
    print(e)

Values to be encoded are too large for representation in the field.


In [10]:
try:
    encoding.encode(-2**63, field)
except Exception as e:
    print(e)

Values to be encoded are too large for representation in the field.


In [11]:
a = encoding.encode(1, field)
encoding.decode(a, field)

1.0

In [12]:
a = encoding.encode([1.5, 2], field)
encoding.decode(a, field)

array([1.5, 2. ])

In [13]:
a = encoding.encode(-1.5, field)
encoding.decode(a, field)

-1.5