# Absolute Value

In this example, we generate a 2x2 matrix of values selected uniformly at random from the field. Then we will reveal them so we can check correctness of the protocol.

Next we will call the absolute method on the secret_share which will calculate the ablsolute value of the matrix on an elementwise basis and return the shared result. This we reveal and decode and print to check against what we would expect given the original secrets.

As you can see from inspection the result of the protocol satifies the desired functionality of what one would expect from absolute value.

In [2]:
import logging

In [3]:
import numpy

In [4]:
import cicada.additive
import cicada.communicator

In [5]:
logging.basicConfig(level=logging.INFO)

In [6]:
@cicada.communicator.NNGCommunicator.run(world_size=3)
def main(communicator):
    log = cicada.Logger(logging.getLogger(), communicator)
    protocol = cicada.additive.AdditiveProtocol(communicator)
    generator = numpy.random.default_rng()
    secret_share = protocol.uniform(shape=(2,2))
    secret = protocol.encoder.decode(protocol.reveal(secret_share))
    log.info(f"Player {communicator.rank} secret: \n{secret}")
    absolute_share = protocol.absolute(secret_share)
    absolute = protocol.encoder.decode(protocol.reveal(absolute_share))
    log.info(f"Player {communicator.rank} absolute(secret): \n{absolute}")
    


In [7]:
main()

INFO:cicada.communicator.nng:Player 0 rendezvous with tcp://127.0.0.1:62937 from tcp://127.0.0.1:62937.
INFO:cicada.communicator.nng:Player 1 rendezvous with tcp://127.0.0.1:62937 from tcp://127.0.0.1:62938.
INFO:cicada.communicator.nng:Player 2 rendezvous with tcp://127.0.0.1:62937 from tcp://127.0.0.1:62939.
INFO:cicada.communicator.nng:Comm 'world' player 0 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 2 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 1 communicator ready.
INFO:root:Player 0 secret: 
[[-6.70366348e+13  1.35850363e+14]
 [ 3.48036470e+13  1.13408667e+14]]
INFO:root:Player 1 secret: 
[[-6.70366348e+13  1.35850363e+14]
 [ 3.48036470e+13  1.13408667e+14]]
INFO:root:Player 2 secret: 
[[-6.70366348e+13  1.35850363e+14]
 [ 3.48036470e+13  1.13408667e+14]]
INFO:root:Player 0 absolute(secret): 
[[6.70366348e+13 1.35850363e+14]
 [3.48036470e+13 1.13408667e+14]]
INFO:root:Player 1 absolute(secret): 
[[6.70366348e+13 1.35850363e+14]
 [

[None, None, None]