# Less than zero

In this example we generate a 2x2 matrix with uniform random generated values from the field and call the less than zero function on those shared secrets. The return from this function is boolean (i.e., field elements 1 and 0, not considering the encoding we use for most artithmetic operations). The returned value is an elementwise application of the less_than_zero function to all matrix elements. Therefore, each matrix position will contain field element 1 if it was negative and 0 if the matrix element in that position was positive.

In the script we reveal both the operands and the results so you can confirm correctness. Notice, on the results of the less_tha_zero function we do not call the decode function.

In [7]:
import logging

In [8]:
import numpy

In [9]:
import cicada.additive
import cicada.communicator

In [10]:
logging.basicConfig(level=logging.INFO)

In [14]:
@cicada.communicator.NNGCommunicator.run(world_size=3)
def main(communicator):
    log = cicada.Logger(logging.getLogger(), communicator)
    protocol = cicada.additive.AdditiveProtocol(communicator)
    generator = numpy.random.default_rng()
    secret_share = protocol.uniform(shape=(2,2))
    secret = protocol.encoder.decode(protocol.reveal(secret_share))
    log.info(f"Player {communicator.rank} secret: \n{secret}")
    ltz_share = protocol.less_than_zero(secret_share)
    ltz = protocol.reveal(ltz_share)
    log.info(f"Player {communicator.rank} less_than_zero: \n{ltz}")

In [15]:
main()

INFO:cicada.communicator.nng:Player 0 rendezvous with tcp://127.0.0.1:56996 from tcp://127.0.0.1:56996.
INFO:cicada.communicator.nng:Player 1 rendezvous with tcp://127.0.0.1:56996 from tcp://127.0.0.1:56997.
INFO:cicada.communicator.nng:Player 2 rendezvous with tcp://127.0.0.1:56996 from tcp://127.0.0.1:56998.
INFO:cicada.communicator.nng:Comm 'world' player 1 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 0 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 2 communicator ready.
INFO:root:Player 0 secret: 
[[-6.26508635e+13  8.28983047e+13]
 [-1.15716512e+14  5.67714433e+13]]
INFO:root:Player 1 secret: 
[[-6.26508635e+13  8.28983047e+13]
 [-1.15716512e+14  5.67714433e+13]]
INFO:root:Player 2 secret: 
[[-6.26508635e+13  8.28983047e+13]
 [-1.15716512e+14  5.67714433e+13]]
INFO:root:Player 0 less_than_zero: 
[[1 0]
 [1 0]]
INFO:root:Player 1 less_than_zero: 
[[1 0]
 [1 0]]
INFO:root:Player 2 less_than_zero: 
[[1 0]
 [1 0]]
INFO:cicada.communicator.

[None, None, None]