# Rectified Linear Unit

In this example we generate random field elements, reveal and decode them, then apply the rectified linear unit function to them. We then reveal the result demonstrating the correctness of the function.

In this setting ReLU is applied on an elementwise basis according to the conventional definition of the funciton i.e.,

$$
ReLU(x) = \left\{
    \begin{array}\\
        0 & if\ x\leq0 \\
        x & if\ x>0
    \end{array}
    \right.
$$
   

In [1]:
import logging

import numpy

import cicada.additive
import cicada.communicator

logging.basicConfig(level=logging.INFO)

@cicada.communicator.NNGCommunicator.run(world_size=3)
def main(communicator):
    log = cicada.Logger(logging.getLogger(), communicator)
    protocol = cicada.additive.AdditiveProtocol(communicator)
    generator = numpy.random.default_rng()
    secret_share = protocol.uniform(shape=(2,2))
    secret = protocol.encoder.decode(protocol.reveal(secret_share))
    log.info(f"Player {communicator.rank} secret:\n{secret}")
    relu_share = protocol.relu(secret_share)
    relu = protocol.encoder.decode(protocol.reveal(relu_share))
    log.info(f"Player {communicator.rank} relu result:\n{relu}")

main();

INFO:cicada.communicator.nng:Player 0 rendezvous with tcp://127.0.0.1:58954 from tcp://127.0.0.1:58954.
INFO:cicada.communicator.nng:Player 1 rendezvous with tcp://127.0.0.1:58954 from tcp://127.0.0.1:58955.
INFO:cicada.communicator.nng:Player 2 rendezvous with tcp://127.0.0.1:58954 from tcp://127.0.0.1:58956.
INFO:cicada.communicator.nng:Comm 'world' player 0 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 2 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 1 communicator ready.
INFO:root:Player 0 secret:
[[-1.34344393e+14  7.31125298e+13]
 [ 3.95225430e+13 -3.97123528e+13]]
INFO:root:Player 1 secret:
[[-1.34344393e+14  7.31125298e+13]
 [ 3.95225430e+13 -3.97123528e+13]]
INFO:root:Player 2 secret:
[[-1.34344393e+14  7.31125298e+13]
 [ 3.95225430e+13 -3.97123528e+13]]
INFO:root:Player 0 relu result:
[[0.00000000e+00 7.31125298e+13]
 [3.95225430e+13 0.00000000e+00]]
INFO:root:Player 1 relu result:
[[0.00000000e+00 7.31125298e+13]
 [3.95225430e+13 