Copyright 2021 National Technology & Engineering Solutions<br>
of Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS,<br>
the U.S. Government retains certain rights in this software.<br>
<br>
Licensed under the Apache License, Version 2.0 (the "License");<br>
you may not use this file except in compliance with the License.<br>
You may obtain a copy of the License at<br>
<br>
   http://www.apache.org/licenses/LICENSE-2.0<br>
<br>
Unless required by applicable law or agreed to in writing, software<br>
distributed under the License is distributed on an "AS IS" BASIS,<br>
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br>
See the License for the specific language governing permissions and<br>
limitations under the License.

In [1]:
import logging

In [2]:
import numpy

In [3]:
import cicada.additive
import cicada.communicator

In [4]:
logging.basicConfig(level=logging.INFO)

In [5]:
@cicada.communicator.NNGCommunicator.run(world_size=3)
def main(communicator):
    log = cicada.Logger(logging.getLogger(), communicator)
    protocol = cicada.additive.AdditiveProtocol(communicator)
    generator = numpy.random.default_rng()
    secret_share = protocol.uniform(shape=(2,2))
    secret = protocol.encoder.decode(protocol.reveal(secret_share))
    log.info(f"Player {communicator.rank} secret:\n{secret}")
    relu_share = protocol.relu(secret_share)
    relu = protocol.encoder.decode(protocol.reveal(relu_share))
    log.info(f"Player {communicator.rank} relu result:\n{relu}")

In this example we generate random field elements, reveal and decode them, then apply the rectified linear unit function to them. We then reveal the result demonstrating the correctness of the function.

In this setting ReLU is applied on an elementwise basis according to the conventional definition of the funciton i.e.,

$$
ReLU(x) = \left\{
    \begin{array}\\
        0 & if\ x\leq0 \\
        x & if\ x>0
    \end{array}
    \right.
$$
   

In [6]:
main()

INFO:cicada.communicator.nng:Player 0 rendezvous with tcp://127.0.0.1:65141 from tcp://127.0.0.1:65141.
INFO:cicada.communicator.nng:Player 1 rendezvous with tcp://127.0.0.1:65141 from tcp://127.0.0.1:65142.
INFO:cicada.communicator.nng:Player 2 rendezvous with tcp://127.0.0.1:65141 from tcp://127.0.0.1:65143.
INFO:cicada.communicator.nng:Comm 'world' player 0 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 1 communicator ready.
INFO:cicada.communicator.nng:Comm 'world' player 2 communicator ready.
INFO:root:Player 0 secret:
[[-1.24964026e+14  6.05489602e+13]
 [-2.71842390e+13  5.33758304e+13]]
INFO:root:Player 1 secret:
[[-1.24964026e+14  6.05489602e+13]
 [-2.71842390e+13  5.33758304e+13]]
INFO:root:Player 2 secret:
[[-1.24964026e+14  6.05489602e+13]
 [-2.71842390e+13  5.33758304e+13]]
INFO:root:Player 0 relu result:
[[0.00000000e+00 6.05489602e+13]
 [0.00000000e+00 5.33758304e+13]]
INFO:root:Player 1 relu result:
[[0.00000000e+00 6.05489602e+13]
 [0.00000000e+00 

[None, None, None]